/**
 * Activity labels and classification patterns
 */

import { ActivityLabel } from '../types'

export const LABEL_METADATA = {
  [ActivityLabel.LEARNING]: {
    name: 'Learning',
    color: '#10b981',
    icon: '📚',
    description: 'Educational content, tutorials, documentation',
  },
  [ActivityLabel.WORKING]: {
    name: 'Working',
    color: '#3b82f6',
    icon: '💼',
    description: 'Work-related tasks, emails, meetings',
  },
  [ActivityLabel.ENTERTAINMENT]: {
    name: 'Entertainment',
    color: '#f59e0b',
    icon: '🎮',
    description: 'Videos, games, streaming',
  },
  [ActivityLabel.SOCIAL]: {
    name: 'Social',
    color: '#8b5cf6',
    icon: '💬',
    description: 'Social media, messaging',
  },
  [ActivityLabel.SHOPPING]: {
    name: 'Shopping',
    color: '#ec4899',
    icon: '🛒',
    description: 'Online shopping, e-commerce',
  },
  [ActivityLabel.OTHER]: {
    name: 'Other',
    color: '#6b7280',
    icon: '📄',
    description: 'Uncategorized activity',
  },
} as const

// URL pattern matching for fast classification
export const URL_PATTERNS: Record<ActivityLabel, RegExp[]> = {
  [ActivityLabel.LEARNING]: [
    /coursera\.com/i,
    /udemy\.com/i,
    /edx\.org/i,
    /khanacademy\.org/i,
    /stackoverflow\.com/i,
    /github\.com\/.*\/blob/i,
    /docs\..*\.com/i,
    /developer\.mozilla\.org/i,
    /w3schools\.com/i,
    /medium\.com\/.*\/(tutorial|guide|learning)/i,
    /youtube\.com\/watch.*\b(tutorial|course|lesson)\b/i,
  ],
  [ActivityLabel.WORKING]: [
    /docs\.google\.com/i,
    /notion\.so/i,
    /slack\.com/i,
    /teams\.microsoft\.com/i,
    /mail\.google\.com/i,
    /outlook\.office\.com/i,
    /asana\.com/i,
    /trello\.com/i,
    /jira\.atlassian\.com/i,
    /monday\.com/i,
    /zoom\.us/i,
  ],
  [ActivityLabel.ENTERTAINMENT]: [
    /youtube\.com\/watch/i,
    /netflix\.com/i,
    /twitch\.tv/i,
    /hulu\.com/i,
    /disneyplus\.com/i,
    /spotify\.com/i,
    /soundcloud\.com/i,
    /reddit\.com\/r\/(funny|memes|gaming|videos)/i,
    /9gag\.com/i,
    /imgur\.com/i,
    /steam\.com/i,
    /epicgames\.com/i,
  ],
  [ActivityLabel.SOCIAL]: [
    /facebook\.com/i,
    /twitter\.com/i,
    /x\.com/i,
    /instagram\.com/i,
    /tiktok\.com/i,
    /linkedin\.com\/feed/i,
    /snapchat\.com/i,
    /reddit\.com(?!\/r\/(funny|memes|gaming|videos))/i,
    /discord\.com/i,
    /whatsapp\.com/i,
    /telegram\.org/i,
  ],
  [ActivityLabel.SHOPPING]: [
    /amazon\.com/i,
    /ebay\.com/i,
    /alibaba\.com/i,
    /aliexpress\.com/i,
    /walmart\.com/i,
    /target\.com/i,
    /bestbuy\.com/i,
    /etsy\.com/i,
    /shopify\.com/i,
  ],
  [ActivityLabel.OTHER]: [],
}

// Keywords for content-based classification
export const KEYWORDS: Record<ActivityLabel, string[]> = {
  [ActivityLabel.LEARNING]: [
    'tutorial',
    'documentation',
    'learn',
    'course',
    'lesson',
    'study',
    'guide',
    'how to',
    'education',
    'training',
    'workshop',
    'lecture',
  ],
  [ActivityLabel.WORKING]: [
    'meeting',
    'email',
    'project',
    'deadline',
    'task',
    'report',
    'document',
    'presentation',
    'spreadsheet',
    'calendar',
    'agenda',
  ],
  [ActivityLabel.ENTERTAINMENT]: [
    'watch',
    'video',
    'movie',
    'game',
    'play',
    'stream',
    'music',
    'podcast',
    'comedy',
    'fun',
    'entertainment',
  ],
  [ActivityLabel.SOCIAL]: [
    'post',
    'comment',
    'like',
    'share',
    'follow',
    'friend',
    'message',
    'chat',
    'social',
    'network',
  ],
  [ActivityLabel.SHOPPING]: [
    'buy',
    'purchase',
    'cart',
    'checkout',
    'price',
    'sale',
    'discount',
    'product',
    'shop',
    'order',
  ],
  [ActivityLabel.OTHER]: [],
}

// Map activity labels to pet states
export const LABEL_TO_PET_STATE = {
  [ActivityLabel.LEARNING]: 'focused',
  [ActivityLabel.WORKING]: 'focused',
  [ActivityLabel.ENTERTAINMENT]: 'happy',
  [ActivityLabel.SOCIAL]: 'excited',
  [ActivityLabel.SHOPPING]: 'excited',
  [ActivityLabel.OTHER]: 'idle',
} as const
